apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword }}