apiVersion: v1
kind: Service
metadata:
  name: {{ include "gavka-api.fullname" . }}
  labels:
{{ include "gavka-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5005
      targetPort: jdwp
      protocol: TCP
      name: jdwp
  selector:
    app.kubernetes.io/name: {{ include "gavka-api.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
